version: "3"

services:
  trash-email-service:
    build: ./TrashEmailService
    networks:
      - trash-email-network
    ports:
      - "9090:9090"
    volumes:
      - "./DB:/opt/TrashEmailService/DB:rw"
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE

  emails-to-telegram-service:
    build: ./EmailsToTelegramService
    networks:
      - trash-email-network
    restart: on-failure
    depends_on:
      - trash-email-service
    volumes:
      - "/tmp:/tmp:rw"
    environment:
      - SPRING_PROFILES_ACTIVE



networks:
  trash-email-network:

